title: Характер в любительской фотографии
subtitle: Книга в процессе написания
author: С. И. Ивасюк
description: >
  Cайт содержит информацию, <br>
  которая дает представление о возможностях экспертного центра, etc.
location: Москва
date: true

logo: /assets/img/logo.png

baseurl: "https://refbook.ru/"

collections:
  docs:
      output: true
      permalink: '/:collection/:path/'
      layout: doc
  contents:
      output: true
      permalink: '/:collection/:path/'
      layout: text
  archives:
      output: true
      permalink: '/:collection/:path/'
      layout: doc

# Build settings
exclude: README.md
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-roman
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      toc: true
